(function(){
  'use strict';
  const state={precincts:[],map:null,layer:null};const $=id=>document.getElementById(id);const num=value=>{const n=Number(value);return Number.isFinite(n)?n:null};const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
  const code=item=>item?.precinct_ward||item?.code||item?.precinct||'Unknown';const registered=item=>num(item?.registered_voters??item?.registered??item?.total_registered);const population=item=>num(item?.adult_population??item?.voting_age_population??item?.vap);
  function rate(item){const stored=num(item?.registration_rate),pop=population(item),reg=registered(item);const value=stored!=null?(stored>1.5?stored/100:stored):(pop>0&&reg!=null?reg/pop:null);return value!=null&&value>=0&&value<=1?value:null}function rateClass(v){return v==null?'unknown':v<.6?'low':v<.85?'medium':'high'}function fmt(v){return v==null?'—':Number(v).toLocaleString()}function ratePill(item){const v=rate(item);return `<span class="rate ${rateClass(v)}">${v==null?'Review':(v*100).toFixed(1)+'%'}</span>`}
  function table(rows){if(!rows.length)return '<div class="empty-state"><p>No matching verified records are available.</p></div>';return `<table><thead><tr><th>Precinct</th><th>Ward</th><th>Registered</th><th>Adult Pop.</th><th>Reg. Rate</th></tr></thead><tbody>${rows.map(item=>`<tr><td><strong>${esc(code(item))}</strong></td><td>${esc(item.ward??'—')}</td><td>${fmt(registered(item))}</td><td>${fmt(population(item))}</td><td>${ratePill(item)}</td></tr>`).join('')}</tbody></table>`}function priority(){return state.precincts.filter(item=>population(item)>=200&&rate(item)!=null).sort((a,b)=>rate(a)-rate(b))}
  function render(){const verified=state.precincts.filter(item=>rate(item)!=null);$('total-precincts').textContent=state.precincts.length||349;$('total-registered').textContent=fmt(state.precincts.reduce((s,i)=>s+(registered(i)||0),0)||null);$('verified-vap').textContent=fmt(verified.reduce((s,i)=>s+(population(i)||0),0)||null);$('data-summary').textContent=`${state.precincts.length||349} precincts · current registration and outreach data`;$('overview-priority').innerHTML=table(priority().slice(0,10));$('priority-table').innerHTML=table(priority());renderPrecincts()}
  function renderPrecincts(){const q=$('precinct-search').value.trim().toLowerCase();const rows=state.precincts.filter(item=>[code(item),item.ward,item.council_district].join(' ').toLowerCase().includes(q));$('precinct-count').textContent=`${rows.length} records`;$('precinct-table').innerHTML=table(rows)}function message(text){const box=$('message');box.textContent=text;box.classList.toggle('hidden',!text);box.classList.add('error')}
  async function load(){try{const {data,error}=await sb.from('precincts').select('precinct_ward,ward,council_district,registered_voters,adult_population,registration_rate');if(error)throw error;state.precincts=data||[];render()}catch(error){message('The live database could not be read. The map remains available, but population totals are hidden until the connection is restored.');render()}}
  async function initMap(){if(state.map){setTimeout(()=>state.map.invalidateSize(),50);return}state.map=L.map('precinct-map').setView([29.97,-90.07],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:18}).addTo(state.map);try{const response=await fetch('precinct_boundaries.geojson');if(!response.ok)throw new Error(response.status);const geo=await response.json(),lookup=new Map(state.precincts.map(i=>[code(i),i]));state.layer=L.geoJSON(geo,{style:f=>{const v=rate(lookup.get(f.properties.precinct_ward));return{color:'#fff',weight:1,fillOpacity:.72,fillColor:v==null?'#9ca3af':v<.6?'#b23a2e':v<.85?'#d68a2c':'#3f7a5c'}},onEachFeature:(f,l)=>{const item=lookup.get(f.properties.precinct_ward);l.bindPopup(`<strong>${esc(f.properties.precinct_ward)}</strong><br>Registered: ${fmt(registered(item))}<br>Adult population: ${fmt(population(item))}<br>Rate: ${ratePill(item)}`)}}).addTo(state.map);state.map.fitBounds(state.layer.getBounds())}catch(error){message('The precinct boundary map could not be loaded.')}}
  document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===button.dataset.panel));if(button.dataset.panel==='map')initMap()}));$('precinct-search').addEventListener('input',renderPrecincts);load();
})();
